import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import mkcert from 'vite-plugin-mkcert';
import os from 'os';

// Get local network IP address
function getLocalIP() {
  const interfaces = os.networkInterfaces();
  for (const name of Object.keys(interfaces)) {
    for (const iface of interfaces[name]) {
      if (iface.family === 'IPv4' && !iface.internal) {
        return iface.address;
      }
    }
  }
  return null;
}

const localIP = getLocalIP();
const hostnames = ['localhost', '127.0.0.1'];
if (localIP) {
  hostnames.push(localIP);
}

// Get backend URL from environment variable or default to localhost
// Set VITE_BACKEND_URL in .env file to point to shared backend server
// Example: VITE_BACKEND_URL=https://192.168.1.100:8443
const backendURL = process.env.VITE_BACKEND_URL || 'https://localhost:8443';
const backendHost = new URL(backendURL).hostname;

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    mkcert({
      hostnames: hostnames // Include localhost, 127.0.0.1, and your local IP
    })
  ],
  server: {
    host: true, // Expose server on network
    port: 5173,
    https: true, // Enable HTTPS (certificate generated by mkcert plugin)
    hmr: {
      port: 5173,
      clientPort: 5173,
      protocol: 'wss', // Use secure WebSocket for HMR over HTTPS
    },
    proxy: {
      '/api': {
        target: backendURL,
        changeOrigin: true,
        secure: false, // Allow self-signed certificates
        rewrite: (path) => path,
        configure: (proxy, options) => {
          proxy.on('error', (err, req, res) => {
            console.warn('Proxy error:', err.message);
            console.warn(`Make sure the backend server is running on ${backendURL}`);
            console.warn('You can configure the backend URL by setting VITE_BACKEND_URL in .env file');
          });
        }
      },
      '/socket.io': {
        target: backendURL,
        changeOrigin: true,
        secure: false, // Allow self-signed certificates
        ws: true, // Enable WebSocket proxying
        rewrite: (path) => path
      }
    }
  }
});

